/***************************************************************************//**
 *  @file   SampleParticle.hpp
 *  @brief  Definition for the SampleParticle class.
 *
 *  @date   2014-10-14T01:43:09
 *  @autor  generated by ParticleToCode script.
 *          ParticleToCode written by Mitsu(https://github.com/mitsuaki-n).
 ******************************************************************************/
#ifndef __SAMPLE_EFFECTS_SAMPLEPARTICLE_H__
#define __SAMPLE_EFFECTS_SAMPLEPARTICLE_H__

#include "cocos2d.h"

namespace Sample {
namespace Effects {


/**
 *  @brief  SampleParticle class is particle-system of
 *          generated by ParticleToCode.
 */
class SampleParticle : public cocos2d::ParticleSystemQuad
{
public:
    static SampleParticle* create() {
        SampleParticle* ret = new SampleParticle();
        if(ret && ret->init()) {
            ret->autorelease();
        } else {
            CC_SAFE_DELETE(ret);
        }
        return ret;
    }

protected:
    SampleParticle(){}
    virtual ~SampleParticle(){}

    bool init() {
        return initWithTotalParticles(2000.0);
    }
    virtual bool initWithTotalParticles(int number_of_particles);

private:
    SampleParticle(const SampleParticle &) = delete;
    SampleParticle &operator = (const SampleParticle &) = delete;

};

}  // namespace Effects
}  // namespace Sample


#endif  // __SAMPLE_EFFECTS_SAMPLEPARTICLE_H__
